version: "3.8"
# 메트릭 서버 도커
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: ${GF_SIGNUP}
      GF_SECURITY_COOKIE_SAMESITE: ${GF_COOKIE_SAMESITE}
      GF_SECURITY_COOKIE_SECURE: ${GF_COOKIE_SECURE}
      GF_SERVER_ROOT_URL: ${GF_SERVER_ROOT_URL}
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

volumes:
  grafana_data:
  influxdb_data:
  npm_data:
  npm_letsencrypt:

